development:
  host: localhost
  database: appname_development
  identity_map_enabled: true

test:
  host: localhost
  database: appname_test

production:
  # uri: <%= ENV['MONGOLAB_URI'] %>
  
  # -- OR --
  
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
